"""
Temporary file for developing Admin Suite.
"""
import datetime

temp_posts = [
    {
        "id": 1,
        "created_at": datetime.datetime(1990, 1, 28, 9, 4, 55),
        "updated_at": datetime.datetime(2021, 10, 5, 4, 58, 12),
        "published_at": datetime.datetime(2021, 10, 5, 4, 58, 12),
        "state": "published",
        "source": "#1 source text aka markdown",
        "html": "<h1>1 html</h1>",
        "title": "Assume Edge Serve Tax Bank Authority",
        "slug": "assume-edge-serve-tax-bank-authority",
        "description": "A short description describing post 1.",
    },
    {
        "id": 2,
        "created_at": datetime.datetime(1970, 9, 10, 16, 35, 55),
        "updated_at": datetime.datetime(2021, 10, 17, 1, 56, 14),
        "published_at": datetime.datetime(2021, 10, 17, 1, 56, 14),
        "state": "published",
        "source": "#2 source text aka markdown",
        "html": "<h1>2 html</h1>",
        "title": "Watch Particularly Economic Thank Start",
        "slug": "watch-particularly-economic-thank-start",
        "description": "A short description describing post 2.",
    },
    {
        "id": 3,
        "created_at": datetime.datetime(2010, 2, 16, 7, 38, 9),
        "updated_at": datetime.datetime(2021, 10, 7, 1, 9, 37),
        "published_at": datetime.datetime(2021, 10, 7, 1, 9, 37),
        "state": "published",
        "source": "#3 source text aka markdown",
        "html": "<h1>3 html</h1>",
        "title": "Bit Huge World Blue Feel Until Provide Cover",
        "slug": "bit-huge-world-blue-feel-until-provide-cover",
        "description": "A short description describing post 3.",
    },
    {
        "id": 4,
        "created_at": datetime.datetime(1992, 10, 22, 9, 34, 23),
        "updated_at": datetime.datetime(2021, 10, 1, 4, 3, 5),
        "published_at": datetime.datetime(2021, 10, 1, 4, 3, 5),
        "state": "archived",
        "source": "#4 source text aka markdown",
        "html": "<h1>4 html</h1>",
        "title": "Yes Development Remember Environmental Really Information Him",
        "slug": "yes-development-remember-environmental-really-information-him",
        "description": "A short description describing post 4.",
    },
    {
        "id": 5,
        "created_at": datetime.datetime(1995, 8, 30, 4, 30, 24),
        "updated_at": datetime.datetime(2021, 10, 25, 23, 2, 21),
        "published_at": datetime.datetime(2021, 10, 25, 23, 2, 21),
        "state": "draft",
        "source": "#5 source text aka markdown",
        "html": "<h1>5 html</h1>",
        "title": "Guess Throw Fly Fact Opportunity Watch Continue",
        "slug": "guess-throw-fly-fact-opportunity-watch-continue",
        "description": "A short description describing post 5.",
    },
]
