"""posts table

Revision ID: 2db5b9a23855
Revises: ea71761413ea
Create Date: 2021-10-30 15:04:05.823361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2db5b9a23855"
down_revision = "ea71761413ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("html", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_posts_published_at"), "posts", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_posts_slug"), "posts", ["slug"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_slug"), table_name="posts")
    op.drop_index(op.f("ix_posts_published_at"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
